file=open('demo.txt','w')
file.write('hello, how are you')
file.close()
file=open('demo.txt','r')
c=file.read()
print(c)
file.close()
file=open('demo.txt','a')
file.write('\nmay god bless you')
file.close()